name: Build & Test
on:
  pull_request:
    branches:
      - master

jobs:
  scalafmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Coursier dependencies based on OS version and build.sbt
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/
          key: ${{ runner.os }}-build-${{ hashFiles('build.sbt') }}
      - name: Scalafmt
        run: sbt scalafmtCheckAll

  test:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Coursier dependencies based on OS version and build.sbt
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/
          key: ${{ runner.os }}-build-${{ hashFiles('build.sbt') }}
      - name: Run tests
        run: sbt test

  examples:
    name: Compile Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Coursier dependencies based on OS version and build.sbt
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/
          key: ${{ runner.os }}-build-${{ hashFiles('build.sbt') }}
      - name: Compile examples
        run: sbt it:compile

  scapegoat:
    name: Scapegoat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Coursier dependencies based on OS version and build.sbt
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/
          key: ${{ runner.os }}-build-${{ hashFiles('build.sbt') }}
      - name: Run scapegoat
        run: sbt scapegoat